### ISSUE TITLE
Allow the user to select how uncovered lines are displayed

### ISSUE THREAD

**Issue by remy90** [markis/vscode-code-coverage#102]
Previously, we only had the blue squigglely line. We now also have a brown(?) highlight. Initially, I thought I'd accidently installed another coverage tool. My team and I have found this to be somewhat excessive.  Ideally, we'd only have _one_ of these rather than both. Could we make this an extension setting?

For the time being, I've downgraded to v1.9.2

**Comment by swantzter** [comment]
I'd also like to see a setting for this, the brown/orange overlay rather than the squiggly lines causes problems for me seeing the code because of my font colours

**Comment by ronaldohoch** [comment]
+1

**Comment by m-flak** [comment]
Looks like #105 does this guys

**Comment by ronaldohoch** [comment]
Hi @m-flak 

I didn't find that config.. :(

![image](https://github.com/markis/vscode-code-coverage/assets/2287371/ef74e3b8-22b6-4b9f-8edc-94e4a62bb135)
![image](https://github.com/markis/vscode-code-coverage/assets/2287371/f74b9c63-18be-40cc-93eb-cb230b912c0b)

**Comment by 2zqa** [comment]
> I didn't find that config.. :(

That's because the pull request is still open. markis will have to merge it first.

**Comment by ronaldohoch** [comment]
ops, didn't see that 🤦‍♂️

**Comment by markis** [comment]
`1.12.0` has been deployed.  Decorations can now be enabled/disabled through the extension settings.  Also, the colors are defaulted to the named colors, instead of a hard coded color.  Which should work better with different themes.
