### ISSUE TITLE
Code coverage does not display squiggly lines

### ISSUE THREAD

**Issue by stigperez** [markis/vscode-code-coverage#14]
**IDE:** VSCode v. 1.28.2
**Dependencies:**
    "@types/jasmine": "^2.8.9",
    "concurrently": "^4.0.1",
    "jasmine-core": "^3.3.0",
    "karma": "^3.1.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.2",
    "karma-jasmine": "^1.1.2"
**Example:** https://github.com/stigperez/test-typescript-unit-test

I followed the guidelines in regards to the generated lcov coverage file but for some reason I still don't get any squiggly lines in VSCode. I know I technically did not use istanbul but karma-coverage seems to generate the coverage file correctly. Do I need to somehow tell the extension to update the cache or am I missing something obvious here?

**Comment by markis** [comment]
Take a look now. @AlexHaxe did a bunch of work and fixed a lot of issues.
