### ISSUE TITLE
C support

### ISSUE THREAD

**Issue by quackylad** [markis/vscode-code-coverage#21]
I see you added C# support, what about standard C? I might want PHP in the future, is it possible to expand the Extension to highlight any language that can have an lcov.info created for it?

Kind regards, Paul

**Comment by markis** [comment]
I don't think there is any reason it can't support all languages that output an lcov coverage file.  I wonder if vs-code allows wildcards in the languages section?

**Comment by markis** [comment]
If you could take a look and comment on this PR: https://github.com/markis/vscode-code-coverage/pull/22

**Comment by quackylad** [comment]
Sorry, I'm not familiar with GitHub's processes, I presume you've created a problem record (which looks good) and you want consensus that it's the right thing to do?

**Comment by quackylad** [comment]
Ah, you've coded it, am I right in thinking that it's sat on a sccs branch and you'd like me to test it? How do I pull it down?

Alternatively, here are 2 files for testing, the code was executed with argc = 1:-

$ cat main.c

#include <stdio.h>

int main( int argc, char **argv )
{
        if( argc > 1 )
                printf( "YES\n" );
        else if( argc == 1 || argc == 0 )
                printf( "NO\n" );
}
$ cat lcov.info 
TN:
SF:/Users/pas/local/research/coverage/main.c
FN:4,main
FNDA:1,main
FNF:1
FNH:1
BRDA:6,1,0,0
BRDA:6,1,1,1
BRDA:8,0,0,1
BRDA:8,0,1,0
BRF:4
BRH:2
DA:6,1
DA:7,0
DA:8,1
DA:9,1
DA:10,1
LF:5
LH:4
end_of_record

**Comment by yagudaev** [comment]
doesn't the extension right now only work for javascript? I tried to get it to work for ruby, but it didn't load.

**Comment by markis** [comment]
https://github.com/markis/vscode-code-coverage/pull/22 has been deployed in version 1.1.0.

It will now support the main languages vs code supports or if the project contains an `lcov*.info` file.
