### ISSUE TITLE
How do I specify more than one lcov.info file I'd like to use?

### ISSUE THREAD

**Issue by ZempTime** [markis/vscode-code-coverage#26]
I've got files being generated by `jest` and `karma`, which generate their own separate `lcov.info` files. Is it possible to point to both of them?

**Comment by markis** [comment]
You can update `markiscodecoverage.searchCriteria` setting to use a different glob pattern.  The default glob pattern is `coverage/lcov*.info`.

Maybe, your lcov.info files are in coverage/jest/ and coverage/karma/, then you could just use `coverage/*/lcov.info`

If you don't mind the performance hit for searching every directory, you could use `**/lcov.info` and it will use any lcov.info file in your project.

**Comment by BryceBarbara** [comment]
@markis Any chance we could get support for commas or being able to specify an array? The performance hit on a repo at work is really bad doing a deep glob but there isn't enough in common with some of the paths to avoid it.
