### ISSUE TITLE
Extension has no effect

### ISSUE THREAD

**Issue by oliversalzburg** [markis/vscode-code-coverage#28]
I have a `coverage/lcov.info` file, but I neither see a coverage indicator in the status bar nor do I get squiggly lines in my code. Given that there is no configuration to be done, I don't see what I can do to get it working.

**Comment by markis** [comment]
There is an example folder in this repo, would you mind testing it out?

**Comment by oliversalzburg** [comment]
When I try to run that, it errors on the import of `assert`:
```shell
$ npm test

> example@0.0.0 pretest P:\vscode-code-coverage\example
> tsc --lib es6 --outDir out --sourceMap index.ts test.ts

test.ts:1:23 - error TS2307: Cannot find module 'assert'.

1 import { equal } from 'assert';
                        ~~~~~~~~


npm ERR! Test failed.  See above for more details.
```

**Comment by BenjaminWenzel** [comment]
Probably the `package.json` in the example is missing `assert` as dependency ;-)

**Comment by oliversalzburg** [comment]
I thought `assert` is built into Node: https://nodejs.org/api/assert.html But, yeah, with the npm module `assert` it runs and works as expected.

**Comment by oliversalzburg** [comment]
I had excluded the `coverage` folder from VS Code through the `files.exclude` setting. After removing that, the extension works as expected.

**Comment by markis** [comment]
That's good to know!  I wonder if there is a way to over ride that in the extension, I am sure you aren't the last person have this issue.

Regarding the `assert` dependency error that you experienced is related to `typescript` not knowing about `assert`.  I think you needed to run `npm install` or `yarn`. Typescript needs the `@types/node` installed.

**Comment by markis** [comment]
https://github.com/markis/vscode-code-coverage/pull/29
