### ISSUE TITLE
Allow configuration of lcov.info name

### ISSUE THREAD

**Issue by jayongg** [markis/vscode-code-coverage#3]
Can we make the lcov.info file locations configurable?  This way we can incorporate it into our Dev builds produce more easily.

**Comment by markis** [comment]
Sounds good!  I'll work on that next.

**Comment by softEngJason** [comment]
@markis any movement on this?  It would make the difference in me being able to use this extension.

**Comment by markis** [comment]
Big thanks to @AlexHaxe for doing the needful and doing this!
