### ISSUE TITLE
Toggle showing missing coverage

### ISSUE THREAD

**Issue by cjwiseman11** [markis/vscode-code-coverage#38]
Hiya

Great extension - I just wondered if it's possible to enable/disable the squiggly lines? Is there a shortcut or is it only possible by disabling the extension?

Thanks

**Comment by markis** [comment]
There is not anything built in that will disable/enable the squiggly lines.  I think the only way currently is to disable/enable the extension.

This is definitely worth considering in the future.

**Comment by mebibou** [comment]
Was looking for the same functionality... or maybe we could change the color of the lines? if you put them transparent they will disappear

**Comment by JeremyCaron** [comment]
I would love to see this one happen, it's sort of painful to have to disable the whole extension rather than using a keybinding or something in the bottom status bar to toggle it the display.

**Comment by JeremyCaron** [comment]
Thought you should know (for prioritization purposes only) that at least one user has moved on to another extension because of the inactivity on this request.

Looking forward to giving it another try if this ever makes the cut.
