### ISSUE TITLE
Not working with nyc 15.0.1

### ISSUE THREAD

**Issue by alexkreidler** [markis/vscode-code-coverage#51]
I have `nyc` version `15.0.1`, and I'm getting the following errors:

![code-coverage-extension-error](https://user-images.githubusercontent.com/11166947/79033711-63e0e400-7b7e-11ea-9cbd-e993d8891f4b.png)

```
Unable to open 'jsonHover.ts': Unable to read file '/file:/c2/vscode-json-languageservice/src/services/jsonHover.ts' (Error: Unable to resolve non-existing file '/file:/c2/vscode-json-languageservice/src/services/jsonHover.ts').
```

I noticed [this comment](https://github.com/markis/vscode-code-coverage/issues/39#issuecomment-600985558) describing the same issue. They seemed to have resolved it by downgrading their version of `nyc`, which I don't want to do.

Please fix this, this is a great extension otherwise!

**Comment by alexkreidler** [comment]
After doing some debugging, I'm realizing it may not just be the version but actually the fact that this extension has a bug preventing it from working properly with multi-root workspaces in VSCode.

What happens is the extension uses `workspace.rootPath` which defaults to the first workspace root opened. However the `searchCriteria` regex is not absolute and matches the other workspace root, leading for the coverage VSCode "diagnostics" or squiggly lines to be registered with the wrong paths. 

I'm working on a fix for this now.

![Screenshot from 2020-04-11 00-29-13](https://user-images.githubusercontent.com/11166947/79035370-d6a48c00-7b8b-11ea-9a7a-94a817ed70b2.png)

**Comment by alexkreidler** [comment]
Hey @markis thanks for merging the PR.

Would you be able to cut a new release so everyone can get this fix? Thanks!

**Comment by markis** [comment]
Done
