### ISSUE TITLE
Can't get basic functionality to work

### ISSUE THREAD

**Issue by maslade** [markis/vscode-code-coverage#55]
I'm setting up a new repo and am interested in leveraging this extension for my team. My jest.config.js is correctly configured and producing coverage in coverage/*, including `coverage/lcov.info`. But the extension isn't giving me any indicators around missing coverage. How should I troubleshoot this?

jest.config.js
```
const { resolve } = require('path');

module.exports = {
  rootDir: 'src',
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  collectCoverage: true,
  coverageDirectory: resolve(__dirname, 'coverage'),
};
```

**Comment by markis** [comment]
Hey sorry to hear it's not working!  Probably a good place to start is checking to see if the example folder in this project works.  It's the most basic example of how this should work.

**Comment by maslade** [comment]
Great - I will try that and get back to you. Thanks!

**Comment by maslade** [comment]
I cloned the repo and ran `npm install && npm test` from the example directory, but not seeing anything from the extension. I haven't changed the extension settings from their defaults. I've disabled all other extensions and restarted code for good measure, but still no luck.

![image](https://user-images.githubusercontent.com/930769/81712433-93fff900-9442-11ea-8e27-39d73e4c4df3.png)

**Comment by markis** [comment]
Closing, #57 fixes this
