### ISSUE TITLE
Is this intended to work with any lcov.info file?

### ISSUE THREAD

**Issue by lukepighetti** [markis/vscode-code-coverage#60]
I am generating a `coverage/lcov.info` file in a Flutter project but can't get this extension to do anything. Language in use is `dart`.

I also tried to run the example but it failed to generate a coverage file. Perhaps the example could have the coverage file baked into the repo for those of us who aren't in typescript all day? https://github.com/markis/vscode-code-coverage/issues/59

**Comment by Maxim-Filimonov** [comment]
It seem to have activation events for specific language. And dart is not one of them yet.

**Comment by Maxim-Filimonov** [comment]
See #65
