### ISSUE TITLE
How do I start with  Python project?

### ISSUE THREAD

**Issue by felipe1982** [markis/vscode-code-coverage#79]
mkdir coverage
pytest --cov > coverage/lcov.info

Is this how I initalise this extension?

**Comment by markis** [comment]
Does `pytest` output a lcov version of the coverage?  The extension only supports the lcov format.

**Comment by kasanitej** [comment]
@felipe1982 did you find any solution? I can see pytest --cov only generate xml or html or annotate

**Comment by markis** [comment]
Looks like `coverage.py` can output lcov now. And you should be able use coverage.py to run pytest tests.

https://github.com/nedbat/coveragepy/issues/587#issuecomment-1021464744
