### ISSUE TITLE
Not showing indicators

### ISSUE THREAD

**Issue by azatsatklichov** [markis/vscode-code-coverage#88]
I wanted to try this extension, 2 weeks ago it works fine and shows indicators (green, yellow, red) on left side for coverage on opened files (TS, etc.) which has lcov.info, and showing the non-covers errors in problems tab. 
Last one week, this indicator not being showed anymore. I tried it re-installing today again.
Is there any change in extension? Or it is caused some bug. 

Thank you,
Azat

**Comment by jaytarr** [comment]
Looks like last releases were April 21 according to the [tags](https://github.com/markis/vscode-code-coverage/tags). In VS Code there is an option to install an older version. Try that and see if it makes a difference.
