### ISSUE TITLE
n00b question

### ISSUE THREAD

**Issue by geekdave** [markis/vscode-code-coverage#9]
> Ensure your project has generated lcov file(s) using nyc, istanbul or other code coverage tools.

Any recommendations for how to do this with vscode?  I have npm tasks set up to do this from the command line but it would be awesome if there were a happy path for staying in my editor and running mocha tests and generating coverage.

Thanks!

**Comment by markis** [comment]
Mocha has file watcher support with [`--watch`](https://mochajs.org/#min).

I would add that to one of your npm tasks, then open up the terminal in vscode and run the npm task.
