### ISSUE TITLE
Coverage file created - Extension iinstalled - Notheing

### ISSUE THREAD

**Issue by WorikQCI** [markis/vscode-code-coverage#91]
I ran: `flutter test --coverage`
The file `coverage/lcov.info  ` is created
I installed the extension in VSCode: [This](https://marketplace.visualstudio.com/items?itemName=markis.code-coverage)
No `code-coverage.hide` or `code-coverage.show` commands available.

**Comment by adamhoke** [comment]
I have the commands showing up, but activating them does not highlight anything.

Extension version:
v1.8.6

VSCode version about info:

Version: 1.78.1 (Universal)
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
Date: 2023-05-04T09:57:42.343Z (6 days ago)
Electron: 22.5.1
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

**Comment by TarekSalha** [comment]
for me the vscode restart fixed it :-)
