### ISSUE TITLE
Add Default Option or Persistent State for Code Coverage

### ISSUE THREAD

**Issue by veikkoni** [markis/vscode-code-coverage#92]
I primarily utilize the plugin to visualize code coverage while creating or modifying tests. However, when I'm not actively working on tests, I prefer to hide the coverage. This means that on every editor start, I manually run the Hide coverage command. Therefore, it would be beneficial to have a configurable default value for code coverage visibility.

**Comment by markis** [comment]
Can this be closed?

**Comment by markis** [comment]
#93  has been merged and published. Closing, feel free to re-open if needed.
